<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Talkative Text Analyser</title>
    <link rel="stylesheet" href="css/libs/bootstrap.css">
    <link rel="stylesheet" href="css/style.css">
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>

</head>
<body style="font-family:'Lato'; font-weight: 500;
    line-height: 1.1;">
<div class="container row text-center" style="margin: 0; padding: 0; width: 100%;">
    <div class="navbar" style="background: #000000"><img src="images/talkative-logo-co-browsing.png"
                                                         style="width: 300px"></div>
    <div class="container col-xs-8 col-xs-offset-2">
        <h1> Talkative Text Analyser Challenge</h1>
        <h3>Type a text string for analysis</h3>
        <div class="container col-xs-6 col-xs-offset-3">
            <form class="form-group text-center" action="results2" method="post">
                <label>
                    <textarea name="target_text" class="btn form-control"
                              style="border-color: #F9B03D; width: 200px; height: 100px"
                              placeholder="Type or paste your string here"></textarea>
                </label>
                <br><br>
                <input type="submit" name="string" value="Analyse string" class="btn" style="background: #F9B03D; color: #ffffff"/>
            </form>
        </div>
    </div>
    <div class="container col-xs-4 col-xs-offset-4">
        <form action="results" method="post">
            <h3>Choose a text file for analysis </h3>
            <br>
            <input class="form-control form-control-xs name"
                   style="background: #ffffff; color: #000; border-color: #F9B03D" type="text"
                   placeholder="Type a url for your favourite .txt file" name="user_url">
            <br><input name="file" type="submit" value="Analyse .txt file" class="btn row"
                       style="background: #F9B03D; color: #ffffff"/>
        </form>
    </div>
</div>
</body>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
</html>
