<?php
    var_dump($data);
?>

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Text Analyser App</title>
    <link rel="stylesheet" href="css/libs/bootstrap.css">
    <link rel="stylesheet" href="css/style.css">
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>

</head>
<body>
    <div class="container row text-center wrapper">
        <div class="navbar">
            <h1 style="color: orange"><b> Text Analyser App </b></h1>
        </div>
        <div class="container col-xs-8 col-xs-offset-2">
            <h3>Type a text string for analysis</h3>
            <div class="container col-xs-6 col-xs-offset-3">
                <form class="form-group text-center" action="string-analysis" method="post">
                    <label><textarea name="string" class="target_string" placeholder="Type or paste your string here"></textarea></label>
                    <br><br>
                    <input type="submit" value="Analyse string" class="btn submit"/>
                </form>
            </div>
        </div>
        <div class="container col-xs-4 col-xs-offset-4">
            <form action="file-analysis" method="post">
                <h3>Choose a text file for analysis </h3>
                <br>
                <input class="form-control target_file" type="text"
                       placeholder="Type a url for your favourite .txt file" name="user_url">
                <br>
                <input name="file" type="submit" value="Analyse .txt file" class="btn submit"/>
            </form>
        </div>
    </div>
</body>
</html>
